server:
  port: 88

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-router
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: order-router
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: inventory-router
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: user-router
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
    nacos:
      discovery:
        server-addr: 172.31.105.105
