server:
  port: 9000
spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/mall_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  cache:
    type: redis
  redis:
    host: 172.31.105.105
    port: 6379
    password: 123456


  cloud:
    nacos:
      discovery:
        server-addr: 172.31.105.105

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: 172.31.105.105:9876
