server:
  port: 11000
spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/mall_inventory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 172.31.105.105

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
